"""empty message

Revision ID: 50acebc468cf
Revises: e3d06d036305
Create Date: 2020-04-02 21:54:42.712307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50acebc468cf'
down_revision = 'e3d06d036305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts_categories',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('categorie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='cascade')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts_categories')
    # ### end Alembic commands ###
